---
- name: "Install Erlang & Elixir - OSX"
  include_tasks: install-native/osx.yml
  when: ansible_os_family == "Darwin"

- name: "Install Erlang & Elixir - UBUNTU"
  include_tasks: install-native/ubuntu.yml
  when: ansible_os_family == "Debian"

- name: "Set activation cmd"
  set_fact:
    activation_cmd: ". /etc/profile"
