---
- name:  "Install 'erlang' & 'elixir'"
  block:
    - import_tasks: install-native.yml
      when: installation_method == "native"

    - import_tasks: install-asdf.yml
      when: installation_method == "asdf"

- name: "Install `hex`"
  shell: "{{ activation_cmd }} && mix local.hex --force"
  args:
    executable: /bin/bash
  become: no

- name: "Install `rebar`"
  shell: "{{ activation_cmd }} && mix local.rebar --force"
  args:
    executable: /bin/bash
  become: no

- name: "Install Phoenix Framework"
  shell: "{{ activation_cmd }} && mix archive.install https://github.com/phoenixframework/archives/raw/master/phx_new.ez --force"
  args:
    executable: /bin/bash
  become: no
