- name: "Install Erlang & Elixir - OSX"
  include_tasks: erlang-elixir-osx.yml
  when: ansible_os_family == "Darwin"
  
- name: "Install Erlang & Elixir - UBUNTU"
  include_tasks: erlang-elixir-ubuntu.yml
  when: ansible_os_family == "Debian"


- name: "Install `hex`"
  command: mix local.hex --force
  become: no

- name: "Install Phoenix Framework"
  command: mix archive.install https://github.com/phoenixframework/archives/raw/master/phx_new.ez --force
  become: no
