---
- name: "Add Erlang repo to `apt-get`"
  block:
    - name: "Create temp directory 1/2"
      command: "mktemp -d"
      register: mktemp_cmd

    - name: "Create temp directory 2/2"
      set_fact:
        tmp_dir: "{{ mktemp_cmd.stdout }}"

    - name: "Download Repo Package"
      get_url:
        url: "https://packages.erlang-solutions.com/{{ erlang_repo_package }}"
        dest: "{{ tmp_dir }}"

    - name: "Add Repo to `apt-get`"
      command: dpkg -i "{{ erlang_repo_package }}" chdir="{{ tmp_dir }}"
      become: yes
      environment: 
        DEBIAN_FRONTEND: noninteractive

  always:
    - name: "Delete temp directory"
      file:
        state: absent
        path: "{{ tmp_dir }}"
      become: yes

- name: "Install Erlang, Elixir and inotify-tools"
  apt:
    name:
      - erlang
      - elixir
      - inotify-tools
    state: latest
    update_cache: yes
  become: yes
